### [Connect] Available plugins
GET http://localhost:8083/connector-plugins/
Accept: application/json

### [Connect] Configured connectors
GET http://localhost:8083/connectors/
Accept: application/json

### [Connect] Connector status - invoices-source
GET http://localhost:8083/connectors/invoices-source/status
Accept: application/json

### [Connect] Connector status - invoices-source
GET http://localhost:8083/connectors/invoices-source/restart
Accept: application/json

### [Connect] Connector config - invoices-source
GET http://localhost:8083/connectors/invoices-source/config
Accept: application/json

### [Connect] Delete connector - invoices-source
DELETE http://localhost:8083/connectors/invoices-source
Accept: application/json

### [Connect] Create connector for invoices
POST http://localhost:8083/connectors
Accept: application/json
Content-Type: application/json

{
  "name": "invoices-source",
  "config": {
    "tasks.max": "1",
    "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
    "connection.url": "jdbc:mysql://db:3306/invoices",
    "connection.user": "root",
    "connection.password": "toor",
    "topic.prefix": "source-mysql-",
    "poll.interval.ms" : 1000,
    "table.whitelist" : "invoice",
    "mode":"timestamp",
    "timestamp.column.name": "last_updated_at",

    "transforms": "SetValueSchema",
    "transforms.SetValueSchema.type": "org.apache.kafka.connect.transforms.SetSchemaMetadata$Value",
    "transforms.SetValueSchema.schema.name": "com.aiskov.Invoice"
  }
}

### [Connect] Connector status - invoice-items-source
GET http://localhost:8083/connectors/invoice-items-source/status
Accept: application/json

### [Connect] Connector status - invoice-items-source
GET http://localhost:8083/connectors/invoices-source/restart
Accept: application/json

### [Connect] Connector config - invoice-items-source
GET http://localhost:8083/connectors/invoice-items-source/config
Accept: application/json

### [Connect] Delete connector - invoice-items-source
DELETE http://localhost:8083/connectors/invoice-items-source
Accept: application/json

### [Connect] Create connector for invoice items
POST http://localhost:8083/connectors
Accept: application/json
Content-Type: application/json

{
  "name": "invoice-items-source",
  "config": {
    "tasks.max": "1",
    "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
    "connection.url": "jdbc:mysql://db:3306/invoices",
    "connection.user": "root",
    "connection.password": "toor",
    "topic.prefix": "source-mysql-invoice-item",
    "poll.interval.ms" : 1000,
    "query": "SELECT invoice_item.id, invoice_item.invoice_id, invoice_item.name, invoice.last_updated_at FROM invoice_item INNER JOIN invoice ON invoice_item.invoice_id = invoice.id",
    "mode":"timestamp",
    "timestamp.column.name": "last_updated_at",

    "transforms": "SetValueSchema",
    "transforms.SetValueSchema.type": "org.apache.kafka.connect.transforms.SetSchemaMetadata$Value",
    "transforms.SetValueSchema.schema.name": "com.aiskov.Invoice"
  }
}

### [Schema Registry] List all subjects
GET http://localhost:8081/subjects
Accept: application/json

### [Schema Registry] DELETE invoice schema
DELETE http://localhost:8081/subjects/source-mysql-invoice-value
Accept: application/json

### [Schema Registry] Get invoice version
GET http://localhost:8081/subjects/source-mysql-invoice-value/versions
Accept: application/json

### [Schema Registry] Get invoice schema
GET http://localhost:8081/subjects/source-mysql-invoice-value/versions/-1/schema
Accept: application/json

### [Schema Registry] DELETE invoice item schema
DELETE http://localhost:8081/subjects/source-mysql-invoice-item-value
Accept: application/json

### [Schema Registry] Get invoice item version
GET http://localhost:8081/subjects/source-mysql-invoice-item-value/versions
Accept: application/json

### [Schema Registry] Get invoice item schema
GET http://localhost:8081/subjects/source-mysql-invoice-item-value/versions/-1/schema
Accept: application/json
